using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SchemeGenerator.SourceGenerators;

[Generator]
public sealed class SchemeGeneratorDefaultsGenerator : IIncrementalGenerator
{
    private const string GenerateAttributeName = "SchemeGenerator.Attributes.GenerateSchemeDefaultsAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var types = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                GenerateAttributeName,
                static (node, _) => node is TypeDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) => GetTypeInfo(ctx))
            .Where(static m => m is not null)!;

        context.RegisterSourceOutput(types, static (spc, model) => Emit(spc, model!));
    }

    private static TypeGenerationModel? GetTypeInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        var properties = typeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic)
            .Where(p => p.GetAttributes().All(a => a.AttributeClass?.ToDisplayString() != "SchemeGenerator.Attributes.SchemeIgnoreAttribute"))
            .ToImmutableArray();

        return new TypeGenerationModel(
            typeSymbol.Name,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            typeSymbol.ContainingNamespace.ToDisplayString(),
            properties);
    }

    private static void Emit(SourceProductionContext context, TypeGenerationModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine();
        sb.AppendLine($"namespace {model.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {model.TypeName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static class {model.TypeName}SchemeDefaults");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static {model.FullyQualifiedType} Create()");
        sb.AppendLine("        {");
        sb.AppendLine($"            return new {model.TypeName}");
        sb.AppendLine("            {");

        foreach (var prop in model.Properties)
        {
            var init = GetPropertyInitializer(prop);
            sb.AppendLine($"                {prop.Name} = {init},");
        }

        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        public static string CreateJson()");
        sb.AppendLine("        {");
        sb.AppendLine("            return JsonSerializer.Serialize(Create());");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource(
            $"{model.TypeName}SchemeDefaults.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string GetPropertyInitializer(IPropertySymbol property)
    {
        var attr = property.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "SchemeValueAttribute");
        if (attr is not null && attr.ConstructorArguments.Length > 0)
        {
            return FormatConstant(attr.ConstructorArguments[0]);
        }

        var type = property.Type;
        if (type.SpecialType != SpecialType.None)
        {
            return PrimitiveLiteral(type.SpecialType);
        }

        if (type.TypeKind == TypeKind.Enum)
        {
            var member = type.GetMembers().OfType<IFieldSymbol>().FirstOrDefault(f => f.HasConstantValue);
            return member is not null ? $"{type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}.{member.Name}" : "default";
        }

        if (property.Type is INamedTypeSymbol named && named.IsGenericType &&
            named.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.List<T>")
        {
            var elem = named.TypeArguments[0];
            return $"new global::System.Collections.Generic.List<{elem.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}> {{ {GetDefaultForType(elem)} }}";
        }

        return $"new global::SchemeGenerator.SchemeGenerator().GetDefault<{type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>()!";
    }

    private static string GetDefaultForType(ITypeSymbol type)
    {
        if (type.SpecialType != SpecialType.None)
        {
            return PrimitiveLiteral(type.SpecialType);
        }

        return $"new global::SchemeGenerator.SchemeGenerator().GetDefault<{type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>()!";
    }

    private static string PrimitiveLiteral(SpecialType specialType) => specialType switch
    {
        SpecialType.System_String => "\"\"",
        SpecialType.System_Boolean => "false",
        SpecialType.System_Char => "'\\0'",
        SpecialType.System_Byte or SpecialType.System_SByte or
        SpecialType.System_Int16 or SpecialType.System_UInt16 or
        SpecialType.System_Int32 or SpecialType.System_UInt32 or
        SpecialType.System_Int64 or SpecialType.System_UInt64 or
        SpecialType.System_Single or SpecialType.System_Double or
        SpecialType.System_Decimal => "0",
        _ => "default"
    };

    private static string FormatConstant(TypedConstant arg)
    {
        return arg.Value switch
        {
            null => "null",
            string s => $"\"{s}\"",
            bool b => b ? "true" : "false",
            _ => arg.ToCSharpString()
        };
    }

    private sealed class TypeGenerationModel
    {
        public TypeGenerationModel(
            string typeName,
            string fullyQualifiedType,
            string @namespace,
            ImmutableArray<IPropertySymbol> properties)
        {
            TypeName = typeName;
            FullyQualifiedType = fullyQualifiedType;
            Namespace = @namespace;
            Properties = properties;
        }

        public string TypeName { get; }
        public string FullyQualifiedType { get; }
        public string Namespace { get; }
        public ImmutableArray<IPropertySymbol> Properties { get; }
    }
}
